version: "3.8"
services:
  api:
    container_name: api
    build:
      context: ../@@.ImportPath@@
      dockerfile: ../build/Dockerfile
    tty: true
    restart: always
    volumes:
      - ..:/app
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DRIVER: "postgres"
      DATABASE_URL: "host=db user=postgres dbname=postgres password=postgres sslmode=disable"
    command: sh scripts/build-local.sh
  db:
    image: postgres:10-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_HOST: localhost
      TZ: 'Asia/Tokyo'
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    volumes:
      - ../test/database/init:/docker-entrypoint-initdb.d
  
